#!/bin/sh
#https://wiki.archlinux.org/index.php/Rofi
rofi -combi-modi window,drun,run -show combi -location 1 -width 100 -lines 5 -line-margin 0 -line-padding 0 -separator-style none -font "monaco 12" -columns 1 -bw 0 -disable-history -hide-scrollbar -color-window "#222222, #b1b4b3, #b1b4b3" -color-normal "#222222, #b1b4b3, #222222, #005577, #b1b4b3" -color-active "#007763, #f5f5f5, #007763, #fb7299, #f5f5f5" -color-urgent "#222222, #b1b4b3, #222222, #77003d, #b1b4b3"
